- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.2
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: pretty-format-json
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: flake8
    args: ['--ignore=E501']
  - id: fix-encoding-pragma
  - id: detect-private-key
- repo: git://github.com/asottile/add-trailing-comma
  sha: v0.6.4
  hooks:
  - id: add-trailing-comma
    exclude: \.py$
- repo: git://github.com/detailyang/pre-commit-shell
  sha: 1.0.2
  hooks:
  - id: shell-lint
