version: '2'

services:
  strataworker-pdf:
    build: .
    image: strataworker-pdf
    environment:
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
