version: '2'

services:
  lambda:
    platform: linux/amd64
    container_name: lambda
    image: public.ecr.aws/sam/build-python3.9
    environment:
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
      - VAULT_TOKEN=$VAULT_TOKEN
      - VAULT_ADDR=$VAULT_ADDR
      - AWS_LAMBDA_EVENT_BODY=$AWS_LAMBDA_EVENT_BODY
      - ENABLE_SENTRY=False
      - LD_LIBRARY_PATH=/opt/lib
      - FONTCONFIG_PATH=/opt/fonts
    working_dir: /var/task
    volumes:
      - ./wkhtmltox:/opt
      - .:/var/task
  mocklambda:
    platform: linux/amd64
    container_name: mocklambda
    image: public.ecr.aws/sam/build-python3.9
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=asdf
      - AWS_SECRET_ACCESS_KEY=asdf
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
      - HOSTNAME=$HOSTNAME
      - ENDPOINT_URL=http://localstack:4566
      - AWS_LAMBDA_EVENT_BODY=$AWS_LAMBDA_EVENT_BODY
      - ENABLE_SENTRY=False
      - LD_LIBRARY_PATH=/opt/lib
      - FONTCONFIG_PATH=/opt/fonts
    working_dir: /var/task
    volumes:
      - ./wkhtmltox:/opt
      - .:/var/task
    networks:
      - mynetwork
    links:
      - localstack
    entrypoint: bash mock_entrypoint.sh
  localstack:
    platform: linux/amd64
    image: localstack/localstack
    ports:
      - 4572:4572
      - 4566:4566
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=lambda,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
    networks:
      - mynetwork

networks:
  mynetwork:
